//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message.proto
namespace NodeMaster
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LatLng")]
    public partial class LatLng : global::ProtoBuf.IExtensible
    {
        public LatLng() { }

        private double _lat;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"lat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public double lat
        {
            get { return _lat; }
            set { _lat = value; }
        }
        private double _lng;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"lng", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public double lng
        {
            get { return _lng; }
            set { _lng = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"AgeModel")]
    public partial class AgeModel : global::ProtoBuf.IExtensible
    {
        public AgeModel() { }

        private uint _Value = default(uint);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(uint))]
        public uint Value
        {
            get { return _Value; }
            set { _Value = value; }
        }
        private string _Unit = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"Unit", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Unit
        {
            get { return _Unit; }
            set { _Unit = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"BloodPressureModel")]
    public partial class BloodPressureModel : global::ProtoBuf.IExtensible
    {
        public BloodPressureModel() { }

        private int _SystolicBloodPressure = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"SystolicBloodPressure", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int SystolicBloodPressure
        {
            get { return _SystolicBloodPressure; }
            set { _SystolicBloodPressure = value; }
        }
        private int _DiastolicBloodPressure = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"DiastolicBloodPressure", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int DiastolicBloodPressure
        {
            get { return _DiastolicBloodPressure; }
            set { _DiastolicBloodPressure = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"VitalSignsModel")]
    public partial class VitalSignsModel : global::ProtoBuf.IExtensible
    {
        public VitalSignsModel() { }

        private NodeMaster.BloodPressureModel _BloodPressure = null;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"BloodPressure", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.BloodPressureModel BloodPressure
        {
            get { return _BloodPressure; }
            set { _BloodPressure = value; }
        }
        private int _PulseRate = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"PulseRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int PulseRate
        {
            get { return _PulseRate; }
            set { _PulseRate = value; }
        }
        private int _RespiratoryRate = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"RespiratoryRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int RespiratoryRate
        {
            get { return _RespiratoryRate; }
            set { _RespiratoryRate = value; }
        }
        private double _Temperature = default(double);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"Temperature", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(double))]
        public double Temperature
        {
            get { return _Temperature; }
            set { _Temperature = value; }
        }
        private ulong _DateTime = default(ulong);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"DateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(ulong))]
        public ulong DateTime
        {
            get { return _DateTime; }
            set { _DateTime = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"TriageInfoModel")]
    public partial class TriageInfoModel : global::ProtoBuf.IExtensible
    {
        public TriageInfoModel() { }

        private string _ReportProviderId = "";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"ReportProviderId", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ReportProviderId
        {
            get { return _ReportProviderId; }
            set { _ReportProviderId = value; }
        }
        private string _ReportId = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"ReportId", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ReportId
        {
            get { return _ReportId; }
            set { _ReportId = value; }
        }
        private ulong _ReportDateTime = default(ulong);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"ReportDateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(ulong))]
        public ulong ReportDateTime
        {
            get { return _ReportDateTime; }
            set { _ReportDateTime = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"HelpBeaconModel")]
    public partial class HelpBeaconModel : global::ProtoBuf.IExtensible
    {
        public HelpBeaconModel() { }

        private string _ID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string ID
        {
            get { return _ID; }
            set { _ID = value; }
        }
        private string _BasicID = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"BasicID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string BasicID
        {
            get { return _BasicID; }
            set { _BasicID = value; }
        }
        private string _Message = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"Message", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get { return _Message; }
            set { _Message = value; }
        }
        private ulong _LastScanDateTime = default(ulong);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"LastScanDateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(ulong))]
        public ulong LastScanDateTime
        {
            get { return _LastScanDateTime; }
            set { _LastScanDateTime = value; }
        }
        private bool _Notified = default(bool);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"Notified", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool Notified
        {
            get { return _Notified; }
            set { _Notified = value; }
        }
        private bool _Rescued = default(bool);
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"Rescued", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool Rescued
        {
            get { return _Rescued; }
            set { _Rescued = value; }
        }
        private bool _Safe = default(bool);
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"Safe", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool Safe
        {
            get { return _Safe; }
            set { _Safe = value; }
        }
        private ulong _AdvertisedDateTime = default(ulong);
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"AdvertisedDateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(ulong))]
        public ulong AdvertisedDateTime
        {
            get { return _AdvertisedDateTime; }
            set { _AdvertisedDateTime = value; }
        }
        private string _Name = "";
        [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }
        private string _Imei = "";
        [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name = @"Imei", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Imei
        {
            get { return _Imei; }
            set { _Imei = value; }
        }
        private string _Source = "";
        [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name = @"Source", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source
        {
            get { return _Source; }
            set { _Source = value; }
        }
        private ulong _Time = default(ulong);
        [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name = @"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(ulong))]
        public ulong Time
        {
            get { return _Time; }
            set { _Time = value; }
        }
        private NodeMaster.LatLng _Location = null;
        [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name = @"Location", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.LatLng Location
        {
            get { return _Location; }
            set { _Location = value; }
        }
        private readonly global::System.Collections.Generic.List<NodeMaster.HelpBeaconModel.DictionaryEntry> _DistributionDictionay = new global::System.Collections.Generic.List<NodeMaster.HelpBeaconModel.DictionaryEntry>();
        [global::ProtoBuf.ProtoMember(14, Name = @"DistributionDictionay", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<NodeMaster.HelpBeaconModel.DictionaryEntry> DistributionDictionay
        {
            get { return _DistributionDictionay; }
        }

        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DictionaryEntry")]
        public partial class DictionaryEntry : global::ProtoBuf.IExtensible
        {
            public DictionaryEntry() { }

            private string _key;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string key
            {
                get { return _key; }
                set { _key = value; }
            }
            private string _value;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string value
            {
                get { return _value; }
                set { _value = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"IncidentObjectModel")]
    public partial class IncidentObjectModel : global::ProtoBuf.IExtensible
    {
        public IncidentObjectModel() { }

        private string _ID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string ID
        {
            get { return _ID; }
            set { _ID = value; }
        }
        private string _GraphicValue = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"GraphicValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string GraphicValue
        {
            get { return _GraphicValue; }
            set { _GraphicValue = value; }
        }
        private string _Description = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return _Description; }
            set { _Description = value; }
        }
        private double _Floor = default(double);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"Floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(double))]
        public double Floor
        {
            get { return _Floor; }
            set { _Floor = value; }
        }
        private double _Elevation = default(double);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"Elevation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(double))]
        public double Elevation
        {
            get { return _Elevation; }
            set { _Elevation = value; }
        }
        private readonly global::System.Collections.Generic.List<NodeMaster.LatLng> _LinearRingPointList = new global::System.Collections.Generic.List<NodeMaster.LatLng>();
        [global::ProtoBuf.ProtoMember(6, Name = @"LinearRingPointList", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<NodeMaster.LatLng> LinearRingPointList
        {
            get { return _LinearRingPointList; }
        }

        private NodeMaster.LatLng _Location = null;
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"Location", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.LatLng Location
        {
            get { return _Location; }
            set { _Location = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MediaModel")]
    public partial class MediaModel : global::ProtoBuf.IExtensible
    {
        public MediaModel() { }

        private string _ID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string ID
        {
            get { return _ID; }
            set { _ID = value; }
        }
        private string _Title = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"Title", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Title
        {
            get { return _Title; }
            set { _Title = value; }
        }
        private ulong _AvailableDateTime = default(ulong);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"AvailableDateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(ulong))]
        public ulong AvailableDateTime
        {
            get { return _AvailableDateTime; }
            set { _AvailableDateTime = value; }
        }
        private readonly global::System.Collections.Generic.List<string> _Tags = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(4, Name = @"Tags", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> Tags
        {
            get { return _Tags; }
        }

        private string _LocalFileUriString = "";
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"LocalFileUriString", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocalFileUriString
        {
            get { return _LocalFileUriString; }
            set { _LocalFileUriString = value; }
        }
        private string _UriString = "";
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"UriString", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string UriString
        {
            get { return _UriString; }
            set { _UriString = value; }
        }
        private int _Type = default(int);
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int Type
        {
            get { return _Type; }
            set { _Type = value; }
        }
        private NodeMaster.LatLng _Location = null;
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"Location", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.LatLng Location
        {
            get { return _Location; }
            set { _Location = value; }
        }
        private string _Description = "";
        [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return _Description; }
            set { _Description = value; }
        }
        private string _Author = "";
        [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name = @"Author", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Author
        {
            get { return _Author; }
            set { _Author = value; }
        }
        private string _SubeventKeywords = "";
        [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name = @"SubeventKeywords", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string SubeventKeywords
        {
            get { return _SubeventKeywords; }
            set { _SubeventKeywords = value; }
        }
        private string _GroupName = "";
        [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name = @"GroupName", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string GroupName
        {
            get { return _GroupName; }
            set { _GroupName = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MessengerModel")]
    public partial class MessengerModel : global::ProtoBuf.IExtensible
    {
        public MessengerModel() { }

        private string _ID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string ID
        {
            get { return _ID; }
            set { _ID = value; }
        }
        private string _SenderID = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"SenderID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string SenderID
        {
            get { return _SenderID; }
            set { _SenderID = value; }
        }
        private string _ActionPlan = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"ActionPlan", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ActionPlan
        {
            get { return _ActionPlan; }
            set { _ActionPlan = value; }
        }
        private ulong _DateTimeSent = default(ulong);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"DateTimeSent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(ulong))]
        public ulong DateTimeSent
        {
            get { return _DateTimeSent; }
            set { _DateTimeSent = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PatientModel")]
    public partial class PatientModel : global::ProtoBuf.IExtensible
    {
        public PatientModel() { }

        private string _ID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string ID
        {
            get { return _ID; }
            set { _ID = value; }
        }
        private NodeMaster.TriageInfoModel _TriageInfo = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"TriageInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.TriageInfoModel TriageInfo
        {
            get { return _TriageInfo; }
            set { _TriageInfo = value; }
        }
        private NodeMaster.AgeModel _Age = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"Age", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.AgeModel Age
        {
            get { return _Age; }
            set { _Age = value; }
        }
        private string _Sex = "";
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"Sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sex
        {
            get { return _Sex; }
            set { _Sex = value; }
        }
        private NodeMaster.PatientModel.TriageStatusEnum _TriageStatus = NodeMaster.PatientModel.TriageStatusEnum.RED;
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"TriageStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(NodeMaster.PatientModel.TriageStatusEnum.RED)]
        public NodeMaster.PatientModel.TriageStatusEnum TriageStatus
        {
            get { return _TriageStatus; }
            set { _TriageStatus = value; }
        }
        private string _IncidentId = "";
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"IncidentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string IncidentId
        {
            get { return _IncidentId; }
            set { _IncidentId = value; }
        }
        private NodeMaster.LatLng _Location = null;
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"Location", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.LatLng Location
        {
            get { return _Location; }
            set { _Location = value; }
        }
        private string _PersonalIdNumber = "";
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"PersonalIdNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string PersonalIdNumber
        {
            get { return _PersonalIdNumber; }
            set { _PersonalIdNumber = value; }
        }
        private readonly global::System.Collections.Generic.List<NodeMaster.VitalSignsModel> _VitalSigns = new global::System.Collections.Generic.List<NodeMaster.VitalSignsModel>();
        [global::ProtoBuf.ProtoMember(9, Name = @"VitalSigns", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<NodeMaster.VitalSignsModel> VitalSigns
        {
            get { return _VitalSigns; }
        }

        private string _TransferredToDestination = "";
        [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name = @"TransferredToDestination", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string TransferredToDestination
        {
            get { return _TransferredToDestination; }
            set { _TransferredToDestination = value; }
        }
        private bool _Transporting = default(bool);
        [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name = @"Transporting", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool Transporting
        {
            get { return _Transporting; }
            set { _Transporting = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"TriageStatusEnum")]
        public enum TriageStatusEnum
        {

            [global::ProtoBuf.ProtoEnum(Name = @"RED", Value = 1)]
            RED = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"YELLOW", Value = 2)]
            YELLOW = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"GREEN", Value = 3)]
            GREEN = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"BLACK", Value = 4)]
            BLACK = 4,

            [global::ProtoBuf.ProtoEnum(Name = @"WHITE", Value = 5)]
            WHITE = 5
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ResourceMobilizationModel")]
    public partial class ResourceMobilizationModel : global::ProtoBuf.IExtensible
    {
        public ResourceMobilizationModel() { }

        private string _ID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string ID
        {
            get { return _ID; }
            set { _ID = value; }
        }
        private NodeMaster.LatLng _Location = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"Location", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.LatLng Location
        {
            get { return _Location; }
            set { _Location = value; }
        }
        private string _Task = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"Task", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Task
        {
            get { return _Task; }
            set { _Task = value; }
        }
        private int _NumberOfFireVehicles = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"NumberOfFireVehicles", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int NumberOfFireVehicles
        {
            get { return _NumberOfFireVehicles; }
            set { _NumberOfFireVehicles = value; }
        }
        private int _NumberOfFirePersonnel = default(int);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"NumberOfFirePersonnel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int NumberOfFirePersonnel
        {
            get { return _NumberOfFirePersonnel; }
            set { _NumberOfFirePersonnel = value; }
        }
        private int _NumberOfMedicVehicles = default(int);
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"NumberOfMedicVehicles", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int NumberOfMedicVehicles
        {
            get { return _NumberOfMedicVehicles; }
            set { _NumberOfMedicVehicles = value; }
        }
        private int _NumberOfMedicPersonnel = default(int);
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"NumberOfMedicPersonnel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int NumberOfMedicPersonnel
        {
            get { return _NumberOfMedicPersonnel; }
            set { _NumberOfMedicPersonnel = value; }
        }
        private int _NumberOfPoliceVehicles = default(int);
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"NumberOfPoliceVehicles", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int NumberOfPoliceVehicles
        {
            get { return _NumberOfPoliceVehicles; }
            set { _NumberOfPoliceVehicles = value; }
        }
        private int _NumberOfPolicePersonnel = default(int);
        [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"NumberOfPolicePersonnel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int NumberOfPolicePersonnel
        {
            get { return _NumberOfPolicePersonnel; }
            set { _NumberOfPolicePersonnel = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ResourceStatusModel")]
    public partial class ResourceStatusModel : global::ProtoBuf.IExtensible
    {
        public ResourceStatusModel() { }

        private string _ID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string ID
        {
            get { return _ID; }
            set { _ID = value; }
        }
        private string _type = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string type
        {
            get { return _type; }
            set { _type = value; }
        }
        private string _Assignment = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"Assignment", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Assignment
        {
            get { return _Assignment; }
            set { _Assignment = value; }
        }
        private string _Name = "";
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }
        private string _Status = "";
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"Status", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Status
        {
            get { return _Status; }
            set { _Status = value; }
        }
        private NodeMaster.LatLng _Location = null;
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"Location", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.LatLng Location
        {
            get { return _Location; }
            set { _Location = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Transaction")]
    public partial class Transaction : global::ProtoBuf.IExtensible
    {
        public Transaction() { }

        private NodeMaster.Transaction.Content _PublishList = null;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"PublishList", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.Transaction.Content PublishList
        {
            get { return _PublishList; }
            set { _PublishList = value; }
        }
        private NodeMaster.Transaction.Content _RemoveList = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"RemoveList", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NodeMaster.Transaction.Content RemoveList
        {
            get { return _RemoveList; }
            set { _RemoveList = value; }
        }
        private string _SenderID;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"SenderID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string SenderID
        {
            get { return _SenderID; }
            set { _SenderID = value; }
        }
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Content")]
        public partial class Content : global::ProtoBuf.IExtensible
        {
            public Content() { }

            private readonly global::System.Collections.Generic.List<NodeMaster.HelpBeaconModel> _HelpBeaconList = new global::System.Collections.Generic.List<NodeMaster.HelpBeaconModel>();
            [global::ProtoBuf.ProtoMember(1, Name = @"HelpBeaconList", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<NodeMaster.HelpBeaconModel> HelpBeaconList
            {
                get { return _HelpBeaconList; }
            }

            private readonly global::System.Collections.Generic.List<NodeMaster.IncidentObjectModel> _IncidentObjectList = new global::System.Collections.Generic.List<NodeMaster.IncidentObjectModel>();
            [global::ProtoBuf.ProtoMember(2, Name = @"IncidentObjectList", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<NodeMaster.IncidentObjectModel> IncidentObjectList
            {
                get { return _IncidentObjectList; }
            }

            private readonly global::System.Collections.Generic.List<NodeMaster.MediaModel> _MediaList = new global::System.Collections.Generic.List<NodeMaster.MediaModel>();
            [global::ProtoBuf.ProtoMember(3, Name = @"MediaList", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<NodeMaster.MediaModel> MediaList
            {
                get { return _MediaList; }
            }

            private readonly global::System.Collections.Generic.List<NodeMaster.MessengerModel> _MessengerList = new global::System.Collections.Generic.List<NodeMaster.MessengerModel>();
            [global::ProtoBuf.ProtoMember(4, Name = @"MessengerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<NodeMaster.MessengerModel> MessengerList
            {
                get { return _MessengerList; }
            }

            private readonly global::System.Collections.Generic.List<NodeMaster.PatientModel> _PatientList = new global::System.Collections.Generic.List<NodeMaster.PatientModel>();
            [global::ProtoBuf.ProtoMember(5, Name = @"PatientList", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<NodeMaster.PatientModel> PatientList
            {
                get { return _PatientList; }
            }

            private readonly global::System.Collections.Generic.List<NodeMaster.ResourceMobilizationModel> _ResourceMobilizationList = new global::System.Collections.Generic.List<NodeMaster.ResourceMobilizationModel>();
            [global::ProtoBuf.ProtoMember(6, Name = @"ResourceMobilizationList", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<NodeMaster.ResourceMobilizationModel> ResourceMobilizationList
            {
                get { return _ResourceMobilizationList; }
            }

            private readonly global::System.Collections.Generic.List<NodeMaster.ResourceStatusModel> _ResourceStatusList = new global::System.Collections.Generic.List<NodeMaster.ResourceStatusModel>();
            [global::ProtoBuf.ProtoMember(7, Name = @"ResourceStatusList", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<NodeMaster.ResourceStatusModel> ResourceStatusList
            {
                get { return _ResourceStatusList; }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}